### ISSUE TITLE
releasing the project name on Pypi?

### ISSUE THREAD

**Issue by jeanbaptisteb** [genedan/contingency#1]
Hello,

Your project name "contingency" is registered on pypi (https://pypi.org/project/contingency/) but it looks like it is empty since 2020. No problem with that, but I was planning to publish a package with the same name on Pypi! 

If your project is no longer active or if you abandoned it, I can request the name to be released on pypi.org through this form (https://github.com/pypi/support/issues/new?assignees=&labels=PEP+541&projects=&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME), so I can use the name for my own project. Can I do that, or do you prefer to keep the name on pypi?

Thanks,

**Comment by genedan** [comment]
You can have it, I don't need the name anymore. Let me know what your pypi user name is and I'll add you as the owner. Then you can remove me from it and use it as you wish.

**Comment by jeanbaptisteb** [comment]
Thanks! This is https://pypi.org/user/jbber/.

**Comment by genedan** [comment]
I've sent you the invite, it should be all yours now.

**Comment by jeanbaptisteb** [comment]
Great, thank you! I removed you from the project on pypi.
